# SPDX-License-Identifier: GPL-2.0-or-later OR BSD-3-Clause
#
# Copyright (C) 2022, STMicroelectronics - All Rights Reserved
# Copyright (C) 2024, Digi International Inc - All Rights Reserved
#

obj-y += ccmp25-dvk.o
