# SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause
#
# Copyright (C) 2018, STMicroelectronics - All Rights Reserved
# Copyright (C) 2022, Digi International Inc - All Rights Reserved
#

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
else
obj-y += ccmp13_dvk.o
endif
